apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke-care-frontend
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: poke-care-frontend
  template:
    metadata:
      labels:
        app: poke-care-frontend
    spec:
      containers:
      - name: poke-care-frontend
        image: darkitote/pokecare-frontend:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: poke-care-config
        resources:  
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3  
          
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 5  
