apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokecare-pokecare-chart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokecare
  template:
    metadata:
      labels:
        app: pokecare
    spec:
      containers:
      - name: pokecare-app
        image: your-pokecare-image:latest
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080