apiVersion: v1
kind: Service
metadata:
  name: poke-care-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.deployment.frontend.containerPort }}
  selector:
    app: poke-care-frontend
