image:
  backend:
    repository: darkitote/pokecare-backend
    tag: latest
  frontend:
    repository: darkitote/pokecare-frontend
    tag: latest

service:
  backend:
    type: ClusterIP
    port: 3000
  frontend:
    type: NodePort
    port: 32010

deployment:
  backend:
    replicas: 2
    containerPort: 3000
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  frontend:
    replicas: 2
    containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

serviceAccount:
  create: false  
ingress:
  enabled: false  

autoscaling:
  enabled: false  