name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Configure Kubernetes credentials
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.MY_KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config  # Asegura que el archivo tenga permisos correctos

    - name: Setup authentication for GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: echo "GitHub authentication set"

    - name: Deploy application using Helm
      env:
        KUBECONFIG: $HOME/.kube/config
      run: |
        helm upgrade --install pokecare ./pokecare-chart --namespace default --wait
